name: Slack
slug: slack
access: public

description: "Slack integration"

category: notification

tags: 
- slack
- notification
- chat

developer:
  name: Subin T P
  email: subin@thoughtwoot.com
  twitter: "@pranav7"
  github: 'pranav7'
